<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use App\Models\User;
use App\Models\Game;
use App\Models\Genre;
use App\Models\GamePost;

class IndieGamesSeeder extends Seeder
{
    public function run(): void
    {
        // ─── ADMIN ────────────────────────────────────────────────
        $admin = User::create([
            'name'     => 'Admin',
            'email'    => 'admin@indiegameconnect.com',
            'password' => Hash::make('password'),
            'role'     => 'admin',
        ]);

        // ─── DEVELOPERS ───────────────────────────────────────────
        $developers = [
            ['name' => 'Team Cherry',         'email' => 'teamcherry@indiegameconnect.com',   'profile_img' => 'img/developers/teamcherry.png'],
            ['name' => 'Extremely OK Games',  'email' => 'extremelyok@indiegameconnect.com',  'profile_img' => 'img/developers/exOKgames.png'],
            ['name' => 'ConcernedApe',        'email' => 'concernedape@indiegameconnect.com', 'profile_img' => 'img/developers/concernedape.jpeg'],
            ['name' => 'Giant Sparrow',       'email' => 'giantsparrow@indiegameconnect.com', 'profile_img' => 'img/developers/giant_sparrow.png'],
            ['name' => 'Toby Fox',            'email' => 'tobyfox@indiegameconnect.com',      'profile_img' => 'img/developers/toby_fox.webp'],
            ['name' => 'Nomada Studio',       'email' => 'nomadastudio@indiegameconnect.com', 'profile_img' => 'img/developers/nomada_studio.png'],
            ['name' => 'Massive Monster',     'email' => 'massivemonster@indiegameconnect.com','profile_img' => 'img/developers/massive_monster.jpg'],
            ['name' => 'Lucas Pope',          'email' => 'lucaspope@indiegameconnect.com',    'profile_img' => 'img/developers/lucas_pope.png'],
            ['name' => 'Campo Santo',         'email' => 'camposanto@indiegameconnect.com',   'profile_img' => 'img/developers/campo_santo.jpeg'],
            ['name' => 'Infinite Fall',       'email' => 'infinitefall@indiegameconnect.com', 'profile_img' => 'img/developers/infinite_fall.png'],
            ['name' => 'MINTROCKET',          'email' => 'mintrocket@indiegameconnect.com',   'profile_img' => 'img/developers/mintrocket.png'],
            ['name' => 'Edmund McMillen',     'email' => 'edmundmcmillen@indiegameconnect.com','profile_img' => 'img/developers/edmund_mcmillen.jpg'],
            ['name' => 'Supergiant Games',    'email' => 'supergiant@indiegameconnect.com',   'profile_img' => 'img/developers/supergiant_games.png'],
            ['name' => 'The Game Kitchen',    'email' => 'gamekitchen@indiegameconnect.com',  'profile_img' => 'img/developers/the_game_kitchen.png'],
            ['name' => 'Motion Twin',         'email' => 'motiontwin@indiegameconnect.com',   'profile_img' => 'img/developers/motion_twin.png'],
            ['name' => 'LocalThunk',          'email' => 'localthunk@indiegameconnect.com',   'profile_img' => 'img/developers/localthunk.png'],
            ['name' => 'Mega Crit Games',     'email' => 'megacrit@indiegameconnect.com',     'profile_img' => 'img/developers/megacrit.webp'],
            ['name' => 'Thunder Lotus Games', 'email' => 'thunderlotus@indiegameconnect.com', 'profile_img' => 'img/developers/thunder_lotus.webp'],
            ['name' => 'GoodbyeWorld Games',  'email' => 'goodbyeworld@indiegameconnect.com', 'profile_img' => 'img/developers/goodbye_world.jpeg'],
            ['name' => 'Daniel Mullins Games','email' => 'danielmullins@indiegameconnect.com','profile_img' => 'img/developers/daniel_mullins.png'],
            ['name' => 'Digital Sun',         'email' => 'digitalsun@indiegameconnect.com',   'profile_img' => 'img/developers/digital_sun.jpg'],
            ['name' => 'Billy Basso',         'email' => 'billybasso@indiegameconnect.com',   'profile_img' => 'img/developers/billy_bassao.webp'],
            ['name' => 'Playdead',            'email' => 'playdead@indiegameconnect.com',     'profile_img' => 'img/developers/playdead.webp'],
            ['name' => 'Coldblood Inc.',      'email' => 'coldblood@indiegameconnect.com',    'profile_img' => 'img/developers/cooldblod_inc.png'],
        ];

        $createdDevs = [];
        foreach ($developers as $dev) {
            $createdDevs[$dev['name']] = User::create([
                'name'        => $dev['name'],
                'email'       => $dev['email'],
                'password'    => Hash::make('password'),
                'role'        => 'developer',
                'profile_img' => $dev['profile_img'],
            ]);
        }

        // ─── GENRES (recuperar de BD) ──────────────────────────────
        $genres = Genre::all()->keyBy('name');

        // ─── JUEGOS ───────────────────────────────────────────────
        $gamesData = [
            [
                'title'        => 'Hollow Knight',
                'description'  => 'Un épico juego de acción y aventura ambientado en un reino subterráneo de insectos. Explora cavernas retorcidas, lucha contra criaturas corrompidas y descubre los secretos de un reino olvidado.',
                'user_id'      => $createdDevs['Team Cherry']->id,
                'release_date' => '2017-02-24',
                'status'       => 'release',
                'engine'       => 'Unity',
                'version'      => '1.5.78',
                'cover_image'  => 'img/games/hollow_knight.webp',
                'download_url' => 'https://store.steampowered.com/app/367520/Hollow_Knight/',
                'genres'       => ['Action', 'Adventure', 'Platformer'],
            ],
            [
                'title'        => 'Hollow Knight: Silksong',
                'description'  => 'La secuela de Hollow Knight. Juega como Hornet, la guerrera princesa, en un nuevo reino lleno de criaturas, héroes y enemigos desconocidos.',
                'user_id'      => $createdDevs['Team Cherry']->id,
                'release_date' => null,
                'status'       => 'alpha',
                'engine'       => 'Unity',
                'version'      => null,
                'cover_image'  => 'img/games/hollow_knight_silksong.webp',
                'download_url' => null,
                'genres'       => ['Action', 'Adventure', 'Platformer'],
            ],
            [
                'title'        => 'Celeste',
                'description'  => 'Ayuda a Madeline a sobrevivir su viaje interior en la cima de la Montaña Celeste en este preciso y desafiante plataformas con una emotiva historia sobre la salud mental.',
                'user_id'      => $createdDevs['Extremely OK Games']->id,
                'release_date' => '2018-01-25',
                'status'       => 'release',
                'engine'       => 'Other',
                'version'      => '1.4.0',
                'cover_image'  => 'img/games/celeste.jpg',
                'download_url' => 'https://store.steampowered.com/app/504230/Celeste/',
                'genres'       => ['Platformer', 'Adventure'],
            ],
            [
                'title'        => 'Earthblade',
                'description'  => 'El próximo proyecto de Extremely OK Games. Un juego de acción y exploración en 2D con pixel art de alta calidad ambientado en un mundo de fantasía.',
                'user_id'      => $createdDevs['Extremely OK Games']->id,
                'release_date' => null,
                'status'       => 'alpha',
                'engine'       => 'Other',
                'version'      => null,
                'cover_image'  => 'img/games/earthblade.png',
                'download_url' => null,
                'genres'       => ['Action', 'Adventure'],
            ],
            [
                'title'        => 'What Remains of Edith Finch',
                'description'  => 'Una colección de historias extrañas sobre una familia en el estado de Washington. Explora la enorme casa Finch descubriendo el pasado de cada miembro de la familia.',
                'user_id'      => $createdDevs['Giant Sparrow']->id,
                'release_date' => '2017-04-25',
                'status'       => 'release',
                'engine'       => 'Unreal',
                'version'      => '1.0',
                'cover_image'  => 'img/games/what_remains_of_edith_finch.jpg',
                'download_url' => 'https://store.steampowered.com/app/501300/What_Remains_of_Edith_Finch/',
                'genres'       => ['Adventure', 'Narrative'],
            ],
            [
                'title'        => 'Stardew Valley',
                'description'  => 'Has heredado la vieja granja de tu abuelo. Con herramientas de segunda mano y monedas en el bolsillo, empiezas tu nueva vida. ¿Podrás convertir los campos en flor en una granja próspera?',
                'user_id'      => $createdDevs['ConcernedApe']->id,
                'release_date' => '2016-02-26',
                'status'       => 'release',
                'engine'       => 'Other',
                'version'      => '1.6.8',
                'cover_image'  => 'img/games/stardew_valley.png',
                'download_url' => 'https://store.steampowered.com/app/413150/Stardew_Valley/',
                'genres'       => ['RPG', 'Simulation'],
            ],
            [
                'title'        => 'Haunted Chocolatier',
                'description'  => 'El nuevo juego del creador de Stardew Valley. Gestiona una chocolatería encantada y explora un mundo mágico lleno de secretos.',
                'user_id'      => $createdDevs['ConcernedApe']->id,
                'release_date' => null,
                'status'       => 'alpha',
                'engine'       => 'Other',
                'version'      => null,
                'cover_image'  => 'img/games/haunted_chocolatier.jpg',
                'download_url' => null,
                'genres'       => ['RPG', 'Simulation'],
            ],
            [
                'title'        => 'Undertale',
                'description'  => 'El RPG donde nadie tiene que morir. Juega como un niño humano caído en el Subsuelo, un reino subterráneo habitado por monstruos. Usa tu ingenio para sobrevivir sin herir a nadie... o no.',
                'user_id'      => $createdDevs['Toby Fox']->id,
                'release_date' => '2015-09-15',
                'status'       => 'release',
                'engine'       => 'GameMaker',
                'version'      => '1.001',
                'cover_image'  => 'img/games/undertale.jpg',
                'download_url' => 'https://store.steampowered.com/app/391540/Undertale/',
                'genres'       => ['RPG', 'Adventure'],
            ],
            [
                'title'        => 'Deltarune',
                'description'  => 'Kris, Susie y Ralsei deben sellar un Oscuro Pozo sellando la Fuente Oscura. Un RPG con combates únicos donde puedes elegir perdonar o luchar contra tus enemigos.',
                'user_id'      => $createdDevs['Toby Fox']->id,
                'release_date' => '2018-10-31',
                'status'       => 'beta',
                'engine'       => 'GameMaker',
                'version'      => '1.10',
                'cover_image'  => 'img/games/deltarune.jpg',
                'download_url' => 'https://store.steampowered.com/app/1671400/Deltarune/',
                'genres'       => ['RPG', 'Adventure'],
            ],
            [
                'title'        => 'GRIS',
                'description'  => 'Una joven que lidia con una experiencia dolorosa en su vida. GRIS es un juego de plataformas contemplativamente pacífico sobre el dolor y los colores de la vida.',
                'user_id'      => $createdDevs['Nomada Studio']->id,
                'release_date' => '2018-12-13',
                'status'       => 'release',
                'engine'       => 'Unity',
                'version'      => '1.04',
                'cover_image'  => 'img/games/gris.webp',
                'download_url' => 'https://store.steampowered.com/app/983870/GRIS/',
                'genres'       => ['Platformer', 'Adventure', 'Narrative'],
            ],
            [
                'title'        => 'Neva',
                'description'  => 'Una mujer y su lobo luchan juntos por sobrevivir en un mundo que se desmorona. Un juego de acción con un vínculo emocional único entre personajes.',
                'user_id'      => $createdDevs['Nomada Studio']->id,
                'release_date' => '2024-10-15',
                'status'       => 'release',
                'engine'       => 'Unity',
                'version'      => '1.0',
                'cover_image'  => 'img/games/neva.jpg',
                'download_url' => 'https://store.steampowered.com/app/2420660/Neva/',
                'genres'       => ['Action', 'Adventure'],
            ],
            [
                'title'        => 'Cult of the Lamb',
                'description'  => 'Recibe el don de la vida de un misterioso extraño y crea un culto a su nombre. Construye una base, dirige a tus seguidores y embárcate en cruzadas para derrotar a los dioses herejes.',
                'user_id'      => $createdDevs['Massive Monster']->id,
                'release_date' => '2022-08-11',
                'status'       => 'release',
                'engine'       => 'Unity',
                'version'      => '1.3.3',
                'cover_image'  => 'img/games/cult_of_the_lamb.jpg',
                'download_url' => 'https://store.steampowered.com/app/1313140/Cult_of_the_Lamb/',
                'genres'       => ['Roguelike', 'Strategy', 'Action'],
            ],
            [
                'title'        => 'Papers, Please',
                'description'  => 'La gloria del Área de Orstón. Trabaja como inspector de inmigración en la ficticia nación totalitaria de Arstotzka y decide quién puede entrar al país.',
                'user_id'      => $createdDevs['Lucas Pope']->id,
                'release_date' => '2013-08-08',
                'status'       => 'release',
                'engine'       => 'Other',
                'version'      => '1.4.12',
                'cover_image'  => 'img/games/papers_please.jpg',
                'download_url' => 'https://store.steampowered.com/app/239030/Papers_Please/',
                'genres'       => ['Strategy', 'Narrative', 'Simulation'],
            ],
            [
                'title'        => 'Firewatch',
                'description'  => 'Es el verano de 1989. Has elegido una vida de soledad como vigilante contra incendios en Wyoming. Tu única conexión con el mundo exterior es una radio y una mujer llamada Delilah.',
                'user_id'      => $createdDevs['Campo Santo']->id,
                'release_date' => '2016-02-09',
                'status'       => 'release',
                'engine'       => 'Unity',
                'version'      => '1.09',
                'cover_image'  => 'img/games/firewatch.jpg',
                'download_url' => 'https://store.steampowered.com/app/383870/Firewatch/',
                'genres'       => ['Adventure', 'Narrative'],
            ],
            [
                'title'        => 'Night in the Woods',
                'description'  => 'Mae Borowski vuelve a casa después de abandonar la universidad y descubre que todo ha cambiado. Un juego de aventuras sobre crecer, amistades y los misterios de un pequeño pueblo.',
                'user_id'      => $createdDevs['Infinite Fall']->id,
                'release_date' => '2017-02-21',
                'status'       => 'release',
                'engine'       => 'Unity',
                'version'      => '3.07',
                'cover_image'  => 'img/games/night_in_the_woods.jpg',
                'download_url' => 'https://store.steampowered.com/app/481510/Night_in_the_Woods/',
                'genres'       => ['Adventure', 'Platformer', 'Narrative'],
            ],
            [
                'title'        => 'Dave the Diver',
                'description'  => 'De día, bucea en las profundidades del océano para capturar peces. De noche, sirve sushi en tu restaurante. Un híbrido único de aventura subacuática y simulación de gestión.',
                'user_id'      => $createdDevs['MINTROCKET']->id,
                'release_date' => '2023-06-28',
                'status'       => 'release',
                'engine'       => 'Unity',
                'version'      => '1.0.2',
                'cover_image'  => 'img/games/dave_the_diver.jpg',
                'download_url' => 'https://store.steampowered.com/app/1868140/DAVE_THE_DIVER/',
                'genres'       => ['Adventure', 'RPG', 'Simulation'],
            ],
            [
                'title'        => 'The Binding of Isaac',
                'description'  => 'Cuando la madre de Isaac recibe un mensaje de Dios exigiendo un sacrificio, Isaac huye al sótano. Un roguelike con temática bíblica oscura y generación procedural.',
                'user_id'      => $createdDevs['Edmund McMillen']->id,
                'release_date' => '2011-09-28',
                'status'       => 'release',
                'engine'       => 'Other',
                'version'      => '1.0',
                'cover_image'  => 'img/games/the_binding_of_isaac.jpg',
                'download_url' => 'https://store.steampowered.com/app/113200/The_Binding_of_Isaac/',
                'genres'       => ['Roguelike', 'Action'],
            ],
            [
                'title'        => 'Hades',
                'description'  => 'Desafía al dios de los muertos mientras intentas escapar del Inframundo griego. Cada intento revela más sobre Zagreus y los secretos de su familia olímpica.',
                'user_id'      => $createdDevs['Supergiant Games']->id,
                'release_date' => '2020-09-17',
                'status'       => 'release',
                'engine'       => 'Other',
                'version'      => '1.38425',
                'cover_image'  => 'img/games/hades.jpg',
                'download_url' => 'https://store.steampowered.com/app/1145360/Hades/',
                'genres'       => ['Roguelike', 'Action', 'RPG'],
            ],
            [
                'title'        => 'Blasphemous',
                'description'  => 'El Milagro ha castigado a la tierra de Cvstodia con una terrible maldición. Juega como el Penitente y avanza con tu espada a través de un mundo de oscuridad y fe distorsionada.',
                'user_id'      => $createdDevs['The Game Kitchen']->id,
                'release_date' => '2019-09-10',
                'status'       => 'release',
                'engine'       => 'Unity',
                'version'      => '4.0.67',
                'cover_image'  => 'img/games/blasphemous.jpg',
                'download_url' => 'https://store.steampowered.com/app/774361/Blasphemous/',
                'genres'       => ['Action', 'Platformer'],
            ],
            [
                'title'        => 'Dead Cells',
                'description'  => 'Un roguelike-metroidvania donde juegas como una masa de células que anima un cadáver. Explora un castillo en constante cambio, muere y aprende de cada derrota.',
                'user_id'      => $createdDevs['Motion Twin']->id,
                'release_date' => '2018-08-07',
                'status'       => 'release',
                'engine'       => 'Other',
                'version'      => '3.5.5',
                'cover_image'  => 'img/games/dead_cells.jpg',
                'download_url' => 'https://store.steampowered.com/app/588650/Dead_Cells/',
                'genres'       => ['Roguelike', 'Action', 'Platformer'],
            ],
            [
                'title'        => 'Balatro',
                'description'  => 'Un juego de póker roguelike donde creas sinergias imposibles con jokers, comodines y modificadores para alcanzar puntuaciones astronómicas. Hipnótico y adictivo.',
                'user_id'      => $createdDevs['LocalThunk']->id,
                'release_date' => '2024-02-20',
                'status'       => 'release',
                'engine'       => 'Other',
                'version'      => '1.0.1n',
                'cover_image'  => 'img/games/balatro.jpg',
                'download_url' => 'https://store.steampowered.com/app/2379780/Balatro/',
                'genres'       => ['Roguelike', 'Strategy'],
            ],
            [
                'title'        => 'Slay the Spire',
                'description'  => 'Fusiónate con mazos únicos, encuentra reliquias de poder inmenso y mata a los monstruos que aguardan en la Aguja. El creador del género roguelike de construcción de mazos.',
                'user_id'      => $createdDevs['Mega Crit Games']->id,
                'release_date' => '2019-01-23',
                'status'       => 'release',
                'engine'       => 'Other',
                'version'      => '2.3',
                'cover_image'  => 'img/games/slay_the_spire.jpg',
                'download_url' => 'https://store.steampowered.com/app/646570/Slay_the_Spire/',
                'genres'       => ['Roguelike', 'Strategy'],
            ],
            [
                'title'        => 'Spiritfarer',
                'description'  => 'Un juego de gestión de barcas cozy sobre la muerte. Juega como Stella, barquera de espíritus, y construye un barco para explorar el mundo, dar cobijo a los espíritus y ayudarlos a despedirse.',
                'user_id'      => $createdDevs['Thunder Lotus Games']->id,
                'release_date' => '2020-08-18',
                'status'       => 'release',
                'engine'       => 'Unity',
                'version'      => '3.7',
                'cover_image'  => 'img/games/spiritfarer.jpg',
                'download_url' => 'https://store.steampowered.com/app/972660/Spiritfarer/',
                'genres'       => ['Adventure', 'Simulation', 'Narrative'],
            ],
            [
                'title'        => 'Before Your Eyes',
                'description'  => 'Un juego narrativo único donde avanzas la historia parpadeando. Revive los recuerdos de una vida entera mientras una misteriosa entidad guía tu alma hacia el más allá.',
                'user_id'      => $createdDevs['GoodbyeWorld Games']->id,
                'release_date' => '2021-04-08',
                'status'       => 'release',
                'engine'       => 'Unity',
                'version'      => '1.6.1',
                'cover_image'  => 'img/games/before_your_eyes.jpg',
                'download_url' => 'https://store.steampowered.com/app/1099600/Before_Your_Eyes/',
                'genres'       => ['Narrative', 'Adventure'],
            ],
            [
                'title'        => 'Inscryption',
                'description'  => 'Un juego de cartas roguelike envuelto en una oscura aventura basada en la narrativa. Descubre los secretos encerrados dentro de este inquietante juego de mazo.',
                'user_id'      => $createdDevs['Daniel Mullins Games']->id,
                'release_date' => '2021-10-19',
                'status'       => 'release',
                'engine'       => 'Unity',
                'version'      => '1.10',
                'cover_image'  => 'img/games/inscryption.webp',
                'download_url' => 'https://store.steampowered.com/app/1092790/Inscryption/',
                'genres'       => ['Roguelike', 'Strategy', 'Narrative'],
            ],
            [
                'title'        => 'Moonlighter',
                'description'  => 'Will es un tendero que sueña con ser héroe. De día gestiona su tienda vendiendo objetos, de noche explora mazmorras peligrosas. Un RPG de acción con mecánicas de comercio.',
                'user_id'      => $createdDevs['Digital Sun']->id,
                'release_date' => '2018-05-29',
                'status'       => 'release',
                'engine'       => 'Unity',
                'version'      => '1.15.00',
                'cover_image'  => 'img/games/moonlighter.jpg',
                'download_url' => 'https://store.steampowered.com/app/606940/Moonlighter/',
                'genres'       => ['RPG', 'Action', 'Roguelike'],
            ],
            [
                'title'        => 'Animal Well',
                'description'  => 'Un metroidvania atmosférico y misterioso donde exploras un mundo subterráneo lleno de criaturas extrañas, puzzles escondidos y secretos que van mucho más allá de lo aparente.',
                'user_id'      => $createdDevs['Billy Basso']->id,
                'release_date' => '2024-05-09',
                'status'       => 'release',
                'engine'       => 'Other',
                'version'      => '1.1.7',
                'cover_image'  => 'img/games/animal_well.jpg',
                'download_url' => 'https://store.steampowered.com/app/813230/ANIMAL_WELL/',
                'genres'       => ['Adventure', 'Platformer'],
            ],
            [
                'title'        => 'Inside',
                'description'  => 'Un juego de plataformas oscuro y atmosférico. Un chico corre, salta y manipula objetos en un mundo monocromático y perturbador lleno de peligros y secretos inquietantes.',
                'user_id'      => $createdDevs['Playdead']->id,
                'release_date' => '2016-06-29',
                'status'       => 'release',
                'engine'       => 'Other',
                'version'      => '1.0',
                'cover_image'  => 'img/games/inside.jpg',
                'download_url' => 'https://store.steampowered.com/app/304430/INSIDE/',
                'genres'       => ['Platformer', 'Adventure'],
            ],
            [
                'title'        => 'Neverway',
                'description'  => 'Fiona deja su trabajo y empieza de cero en una granja de una isla remota, pero se convierte en la heraldo inmortal de un dios muerto. Un RPG de vida y simulación con horror psicológico.',
                'user_id'      => $createdDevs['Coldblood Inc.']->id,
                'release_date' => '2026-10-31',
                'status'       => 'alpha',
                'engine'       => 'Other',
                'version'      => null,
                'cover_image'  => 'img/games/neverway.webp',
                'download_url' => null,
                'genres'       => ['RPG', 'Simulation', 'Adventure'],
            ],
        ];

        $createdGames = [];
        foreach ($gamesData as $gameData) {
            $genreNames = $gameData['genres'];
            unset($gameData['genres']);
            $game = Game::create($gameData);
            $genreIds = collect($genreNames)
                ->map(fn($name) => $genres->get($name)?->id)
                ->filter()->values()->toArray();
            $game->genres()->attach($genreIds);
            $createdGames[$game->title] = $game;
        }

        // ─── POSTS ────────────────────────────────────────────────
        $posts = [
            [
                'game'      => 'Hollow Knight',
                'user_id'   => $createdDevs['Team Cherry']->id,
                'title'     => 'Post',
                'content'   => 'Post de prueba.',
                'image_url' => 'img/posts/hollow_knight_post_1.webp',
            ],
            [
                'game'      => 'Hollow Knight',
                'user_id'   => $createdDevs['Team Cherry']->id,
                'title'     => 'Post',
                'content'   => 'Post de prueba.',
                'image_url' => 'img/posts/hollow_knight_post_2.jpg',
            ],
            [
                'game'      => 'Celeste',
                'user_id'   => $createdDevs['Extremely OK Games']->id,
                'title'     => 'Post',
                'content'   => 'Post de prueba.',
                'image_url' => 'img/posts/celeste_post_1.webp',
            ],
            [
                'game'      => 'Stardew Valley',
                'user_id'   => $createdDevs['ConcernedApe']->id,
                'title'     => 'Post',
                'content'   => 'Post de prueba.',
                'image_url' => 'img/posts/stardew_valley_post_1.jpg',
            ],
            [
                'game'      => 'Stardew Valley',
                'user_id'   => $createdDevs['ConcernedApe']->id,
                'title'     => 'Post',
                'content'   => 'Post de prueba.',
                'image_url' => 'img/posts/stardew_valley_post_2.jpg',
            ],
            [
                'game'      => 'Undertale',
                'user_id'   => $createdDevs['Toby Fox']->id,
                'title'     => 'Post',
                'content'   => 'Post de prueba.',
                'image_url' => 'img/posts/undertale_post_1.jpg',
            ],
            [
                'game'      => 'Deltarune',
                'user_id'   => $createdDevs['Toby Fox']->id,
                'title'     => 'Post',
                'content'   => 'Post de prueba.',
                'image_url' => 'img/posts/deltarune_post_1.png',
            ],
            [
                'game'      => 'Neva',
                'user_id'   => $createdDevs['Nomada Studio']->id,
                'title'     => 'Post',
                'content'   => 'Post de prueba.',
                'image_url' => 'img/posts/neva_post_1.jpg',
            ],
            [
                'game'      => 'Hades',
                'user_id'   => $createdDevs['Supergiant Games']->id,
                'title'     => 'Post',
                'content'   => 'Post de prueba.',
                'image_url' => 'img/posts/hades_post_1.png',
            ],
            [
                'game'      => 'Slay the Spire',
                'user_id'   => $createdDevs['Mega Crit Games']->id,
                'title'     => 'Post',
                'content'   => 'Post de prueba.',
                'image_url' => 'img/posts/slay_the_spire_post_1.jpg',
            ],
            [
                'game'      => 'Neverway',
                'user_id'   => $createdDevs['Coldblood Inc.']->id,
                'title'     => 'Post',
                'content'   => 'Post de prueba.',
                'image_url' => 'img/posts/neverway_post_1.png',
            ],
            [
                'game'      => 'Neverway',
                'user_id'   => $createdDevs['Coldblood Inc.']->id,
                'title'     => 'Post',
                'content'   => 'Post de prueba.',
                'image_url' => 'img/posts/neverway_post_2.jpg',
            ],
        ];

        foreach ($posts as $postData) {
            $game = $createdGames[$postData['game']];
            GamePost::create([
                'game_id'   => $game->id,
                'user_id'   => $postData['user_id'],
                'title'     => $postData['title'],
                'content'   => $postData['content'],
                'image_url' => $postData['image_url'],
            ]);
        }
    }
}